### ISSUE TITLE
xcdn报错

### ISSUE THREAD

**Issue by zjz1525** [3xp10it/xcdn#3]
p4->mechanicalsoup->exp10it) (1.9.1)
'figlet' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "xcdn.py", line 22, in <module>
    figlet2file("3xp10it",0,True)
  File "C:\Users\Tccd\AppData\Local\Programs\Python\Python37\lib\site-packages\exp10it.py", line 1272, in figlet2file
    all_font_name_list = get_all_file_name(figlet_font_dir, ['tlf', 'flf'])
UnboundLocalError: local variable 'figlet_font_dir' referenced before assignment

**Comment by TerickJojo** [comment]
我也遇到这个问题

**Comment by 3xp10it** [comment]
需要在kali下运行
